extends: default

rules:
  braces:
    min-spaces-inside: 0
    max-spaces-inside: 1
    min-spaces-inside-empty: 0
    max-spaces-inside-empty: 0
  indentation:
    spaces: consistent
    check-multi-line-strings: true
  document-start: disable
  empty-values:
    level: warning
    forbid-in-block-mappings: true
    forbid-in-flow-mappings: true
